// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {audio} from '../models';

export function AddFiles(arg1:Array<string>):Promise<Array<main.PlaylistTrack>>;

export function AddFolder(arg1:string):Promise<Array<main.PlaylistTrack>>;

export function AddToPlaylist(arg1:string,arg2:Array<string>):Promise<void>;

export function ClearPlaylist():Promise<void>;

export function CreatePlaylist(arg1:string):Promise<boolean>;

export function DeletePlaylist(arg1:string):Promise<void>;

export function GetCrossfade():Promise<number>;

export function GetInitialState():Promise<main.webConfig>;

export function GetLibraryAlbums():Promise<Array<main.AlbumData>>;

export function GetLibraryArtists():Promise<Array<string>>;

export function GetLibrarySongs():Promise<Array<main.SongData>>;

export function GetLyricOffset(arg1:string,arg2:string):Promise<number>;

export function GetOutputDevice():Promise<string>;

export function GetOutputMode():Promise<string>;

export function GetPlaylist():Promise<Array<main.PlaylistTrack>>;

export function GetPlaylistTracks(arg1:string):Promise<Array<main.PlaylistTrack>>;

export function GetPlaylists():Promise<Array<main.PlaylistMeta>>;

export function GetSpectrum():Promise<Array<number>>;

export function GetVolume():Promise<number>;

export function GetWaveform():Promise<Array<number>>;

export function IsExclusive():Promise<boolean>;

export function IsRepeat():Promise<boolean>;

export function IsShuffle():Promise<boolean>;

export function ListOutputDevices():Promise<Array<audio.OutputDevice>>;

export function LoadAlbum(arg1:string,arg2:string):Promise<main.TrackInfo>;

export function LoadFile(arg1:string):Promise<main.TrackInfo>;

export function MoveTrack(arg1:number,arg2:number):Promise<Array<main.PlaylistTrack>>;

export function Next():Promise<main.TrackInfo>;

export function OpenFileDialog():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function Pause():Promise<void>;

export function Play():Promise<void>;

export function PlayAt(arg1:number):Promise<main.TrackInfo>;

export function PlayPlaylist(arg1:string):Promise<main.TrackInfo>;

export function PlaySong(arg1:string):Promise<main.TrackInfo>;

export function PlaySongs(arg1:Array<string>,arg2:number):Promise<main.TrackInfo>;

export function Prev():Promise<main.TrackInfo>;

export function QueuePlaylist(arg1:string):Promise<Array<main.PlaylistTrack>>;

export function Remove(arg1:number):Promise<Array<main.PlaylistTrack>>;

export function RemoveFromPlaylist(arg1:string,arg2:string):Promise<void>;

export function RenamePlaylist(arg1:string,arg2:string):Promise<boolean>;

export function RetryLyrics():Promise<void>;

export function SaveConfig():Promise<void>;

export function ScanLibrary(arg1:string):Promise<void>;

export function Seek(arg1:number):Promise<void>;

export function SetAccentSource(arg1:string):Promise<void>;

export function SetCrossfade(arg1:number):Promise<void>;

export function SetExclusive(arg1:boolean):Promise<void>;

export function SetLyricOffset(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetOutputDevice(arg1:string):Promise<void>;

export function SetRepeat(arg1:boolean):Promise<void>;

export function SetShuffle(arg1:boolean):Promise<void>;

export function SetVisualizerMode(arg1:string):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function Stop():Promise<void>;

export function UpNext():Promise<main.PlaylistTrack>;
