// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles(arg1) {
  return window['go']['main']['App']['AddFiles'](arg1);
}

export function AddFolder(arg1) {
  return window['go']['main']['App']['AddFolder'](arg1);
}

export function ClearPlaylist() {
  return window['go']['main']['App']['ClearPlaylist']();
}

export function GetCrossfade() {
  return window['go']['main']['App']['GetCrossfade']();
}

export function GetLibraryAlbums() {
  return window['go']['main']['App']['GetLibraryAlbums']();
}

export function GetLibraryArtists() {
  return window['go']['main']['App']['GetLibraryArtists']();
}

export function GetOutputMode() {
  return window['go']['main']['App']['GetOutputMode']();
}

export function GetPlaylist() {
  return window['go']['main']['App']['GetPlaylist']();
}

export function GetVolume() {
  return window['go']['main']['App']['GetVolume']();
}

export function IsExclusive() {
  return window['go']['main']['App']['IsExclusive']();
}

export function IsRepeat() {
  return window['go']['main']['App']['IsRepeat']();
}

export function IsShuffle() {
  return window['go']['main']['App']['IsShuffle']();
}

export function LoadAlbum(arg1, arg2) {
  return window['go']['main']['App']['LoadAlbum'](arg1, arg2);
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function Next() {
  return window['go']['main']['App']['Next']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Play() {
  return window['go']['main']['App']['Play']();
}

export function PlayAt(arg1) {
  return window['go']['main']['App']['PlayAt'](arg1);
}

export function Prev() {
  return window['go']['main']['App']['Prev']();
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function ScanLibrary(arg1) {
  return window['go']['main']['App']['ScanLibrary'](arg1);
}

export function Seek(arg1) {
  return window['go']['main']['App']['Seek'](arg1);
}

export function SetCrossfade(arg1) {
  return window['go']['main']['App']['SetCrossfade'](arg1);
}

export function SetExclusive(arg1) {
  return window['go']['main']['App']['SetExclusive'](arg1);
}

export function SetRepeat(arg1) {
  return window['go']['main']['App']['SetRepeat'](arg1);
}

export function SetShuffle(arg1) {
  return window['go']['main']['App']['SetShuffle'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
