// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOutputMode() {
  return window['go']['main']['App']['GetOutputMode']();
}

export function GetVolume() {
  return window['go']['main']['App']['GetVolume']();
}

export function LoadFile(arg1) {
  return window['go']['main']['App']['LoadFile'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function Play() {
  return window['go']['main']['App']['Play']();
}

export function Seek(arg1) {
  return window['go']['main']['App']['Seek'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
