// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetOutputMode():Promise<string>;

export function GetVolume():Promise<number>;

export function LoadFile(arg1:string):Promise<main.TrackInfo>;

export function OpenFileDialog():Promise<string>;

export function Pause():Promise<void>;

export function Play():Promise<void>;

export function Seek(arg1:number):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function Stop():Promise<void>;
