// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFiles(arg1:Array<string>):Promise<Array<main.PlaylistTrack>>;

export function AddFolder(arg1:string):Promise<Array<main.PlaylistTrack>>;

export function ClearPlaylist():Promise<void>;

export function GetCrossfade():Promise<number>;

export function GetInitialState():Promise<main.webConfig>;

export function GetLibraryAlbums():Promise<Array<main.AlbumData>>;

export function GetLibraryArtists():Promise<Array<string>>;

export function GetLibrarySongs():Promise<Array<main.SongData>>;

export function GetOutputMode():Promise<string>;

export function GetPlaylist():Promise<Array<main.PlaylistTrack>>;

export function GetSpectrum():Promise<Array<number>>;

export function GetVolume():Promise<number>;

export function GetWaveform():Promise<Array<number>>;

export function IsExclusive():Promise<boolean>;

export function IsRepeat():Promise<boolean>;

export function IsShuffle():Promise<boolean>;

export function LoadAlbum(arg1:string,arg2:string):Promise<main.TrackInfo>;

export function LoadFile(arg1:string):Promise<main.TrackInfo>;

export function Next():Promise<main.TrackInfo>;

export function OpenFileDialog():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function Pause():Promise<void>;

export function Play():Promise<void>;

export function PlayAt(arg1:number):Promise<main.TrackInfo>;

export function PlaySong(arg1:string):Promise<main.TrackInfo>;

export function Prev():Promise<main.TrackInfo>;

export function Remove(arg1:number):Promise<Array<main.PlaylistTrack>>;

export function SaveConfig():Promise<void>;

export function ScanLibrary(arg1:string):Promise<void>;

export function Seek(arg1:number):Promise<void>;

export function SetCrossfade(arg1:number):Promise<void>;

export function SetExclusive(arg1:boolean):Promise<void>;

export function SetRepeat(arg1:boolean):Promise<void>;

export function SetShuffle(arg1:boolean):Promise<void>;

export function SetVolume(arg1:number):Promise<void>;

export function Stop():Promise<void>;
