// Package ui provides the Fyne-based graphical interface for Go Music.
package ui

import (
	"crypto/md5"
	_ "embed"
	"fmt"
	"image/color"
	"path/filepath"
	"strings"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/dialog"
	"fyne.io/fyne/v2/driver/desktop"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/storage"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"

	"gomusic/audio"
	"gomusic/library"
	"gomusic/playlist"
)

// appIcon is compiled into the binary so the same image shows up in the
// running window's title-bar / dock entry. The PNG variant is used here
// because Fyne's icon rendering goes through Go's image.Decode, which has
// no .ico support in stdlib — feeding it .ico bytes paints a black box.
// The .exe icon in File Explorer / Start menu comes from
// resource_windows_amd64.syso (generated by `rsrc -ico ui/go_music_icon_1.ico`).
//
//go:embed go_music_icon_1.png
var appIconBytes []byte
var appIconResource = fyne.NewStaticResource("gomusic.png", appIconBytes)

// Inline SVGs for transport buttons that don't have a clean equivalent in
// Fyne's built-in theme. Fill is hard-coded white so the theme can't tint
// them with the accent color when the button is HighImportance — these are
// supposed to stay neutral regardless of toggle state.
var shuffleIconResource = fyne.NewStaticResource("shuffle.svg", []byte(
	`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#ffffff">`+
		`<path d="M10.59 9.17L5.41 4 4 5.41l5.17 5.17 1.42-1.41zM14.5 4l2.04 2.04L4 18.59 5.41 20 17.96 7.46 20 9.5V4h-5.5zm.33 9.41l-1.41 1.41 3.13 3.13L14.5 20H20v-5.5l-2.04 2.04-3.13-3.13z"/>`+
		`</svg>`))

var repeatIconResource = fyne.NewStaticResource("repeat.svg", []byte(
	`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#ffffff">`+
		`<path d="M7 7h10v3l4-4-4-4v3H5v6h2V7zm10 10H7v-3l-4 4 4 4v-3h12v-6h-2v4z"/>`+
		`</svg>`))

// Run starts the Fyne application event loop. Blocks until the window closes.
func Run() {
	a := app.NewWithID("com.gomusic.player")
	a.Settings().SetTheme(gomusicTheme{})
	a.SetIcon(appIconResource)

	w := a.NewWindow("Go Music")
	w.SetIcon(appIconResource)
	// Open at a comfortable size that fits a 1366×768 laptop with taskbar
	// (working area ≈ 728 px tall). Going taller — even though it looks
	// nice on a desktop — gets clamped by the OS on small screens and then
	// the user can't shrink the window because the content's MinSize is
	// already close to that clamped maximum. Users on big monitors can
	// drag-resize or maximize from this baseline.
	w.Resize(fyne.NewSize(1080, 720))
	w.CenterOnScreen()

	cfg := loadConfig()

	eng := audio.NewEngine()
	eng.Volume = cfg.Volume
	eng.SetCrossfade(cfg.CrossfadeSec)
	eng.SetExclusiveMode(cfg.ExclusiveMode)

	pl := playlist.New()
	for _, path := range cfg.PlaylistPaths {
		pl.Add(path)
	}
	if cfg.CurrentIndex >= 0 && cfg.CurrentIndex < pl.Len() {
		pl.SetCurrent(cfg.CurrentIndex)
	}

	ui := buildUI(w, eng, pl, cfg)
	// Load the cached library index (if any) BEFORE the first
	// refreshLibraryUI pass so the Albums / Artists tabs already have
	// content when the window paints. Missing/corrupt cache silently
	// leaves ui.lib nil and the placeholder text shows.
	ui.loadCachedLibrary()
	ui.refreshLibraryUI()
	w.SetContent(ui.root)
	w.SetMainMenu(buildMenu(w, eng, pl, ui))
	ui.installShortcuts(w)

	// Register the OS-level multimedia keys (Play/Pause/Next/Prev) so they
	// work even when the app doesn't have focus. Callbacks fire on a
	// dedicated message-pump thread; we route them through fyne.Do so the
	// UI handlers always run on the Fyne goroutine like every other
	// shortcut path.
	startMediaKeys(mediaKeysHandler{
		OnPlayPause: func() { fyne.Do(ui.togglePlay) },
		OnNext:      func() { fyne.Do(ui.goNext) },
		OnPrev:      func() { fyne.Do(ui.goPrev) },
		OnStop:      func() { fyne.Do(ui.stopPlayback) },
	})

	go ui.runWaveformLoop()

	w.SetOnClosed(func() {
		cfg.Volume = eng.Volume
		cfg.ShowLyrics = ui.showLyrics
		cfg.CurrentIndex = pl.Current
		cfg.CrossfadeSec = eng.CrossfadeSeconds()
		cfg.ExclusiveMode = eng.ExclusiveMode()
		paths := make([]string, len(pl.Tracks))
		for i, t := range pl.Tracks {
			paths[i] = t.Path
		}
		cfg.PlaylistPaths = paths
		cfg.save()
	})

	w.ShowAndRun()
}

// ── UI state ─────────────────────────────────────────────────────────────────

type mainUI struct {
	win        fyne.Window
	cfg        *appConfig
	root       fyne.CanvasObject
	titleText  *canvas.Text
	artistText *canvas.Text
	albumText  *canvas.Text
	formatText *canvas.Text
	posLabel   *canvas.Text
	durLabel   *canvas.Text
	modeLabel  *canvas.Text
	progress   *widget.Slider
	playBtn    *widget.Button
	listWidget *widget.List
	artBg       *canvas.Rectangle
	artImage    *canvas.Image
	artGlyph    *canvas.Text
	bgGradient  *canvas.LinearGradient // album-derived ambient backdrop for the right column
	currentAccent color.NRGBA          // dominant color of the current track (zero when not set)
	eng         *audio.Engine
	pl          *playlist.Playlist
	seeking     bool
	updatingUI  bool
	// suppressSelect guards programmatic listWidget.Select() calls from
	// triggering OnSelected — which would re-enter loadAndPlay and loop.
	suppressSelect bool
	shuffleBtn  *widget.Button
	shuffleDot  *canvas.Circle
	repeatTrack bool // when true, OnFinished restarts the same track instead of advancing
	repeatBtn   *widget.Button
	repeatDot   *canvas.Circle

	// Lyrics panel state
	mainSplit      *container.Split // root horizontal split (playlist | rest)
	rightContainer *fyne.Container  // holds player + optional lyrics panel
	playerColumn   fyne.CanvasObject
	lyricsPanel    fyne.CanvasObject
	lyricsBox      *fyne.Container // VBox of canvas.Text lines
	lyricsScroll   *container.Scroll
	lyricsHeader   *canvas.Text
	lyricsLines    []audio.LyricLine
	currentLyric   int
	showLyrics     bool
	lyricsToken    int              // increments per Load — async fetches check before applying
	lineAnims      []*fyne.Animation // in-flight color/size animations on lyric lines
	scrollAnim     *fyne.Animation   // in-flight smooth-scroll animation

	// Waveform visualizer
	wave *waveformWidget

	// Playlist search/filter
	//
	// `filtered` is the index map applied between the visible list and the
	// underlying pl.Tracks slice. When non-nil it overrides Length/UpdateItem
	// so the list only shows matching rows; nil means "no filter, show all".
	// Selection on a filtered row maps back to the real index before calling
	// pl.SetCurrent, so reordering and Current tracking still operate on the
	// canonical playlist.
	searchEntry *widget.Entry
	searchBar   fyne.CanvasObject
	filtered    []int

	// ── Library view ────────────────────────────────────────────────────
	// lib is the loaded music index; nil until the user picks a music
	// root or a cached library file is loaded on startup. albumGrid and
	// artistList are the two browsing widgets, displayed inside libTabs
	// next to the Playlist tab. artistFilter narrows the album grid down
	// to a single artist when the user clicks one in the Artists tab; an
	// empty string shows every album.
	lib            *library.Library
	libTabs        *container.AppTabs
	albumList      *widget.List
	artistList     *widget.List
	songList       *widget.List    // flat all-tracks list in Songs tab
	allTracks      []*library.Track // source slice for songList
	libStatus      *canvas.Text     // text shown on Albums tab when empty / scanning
	libClearFilter *widget.Button   // "× clear" — visible only when artistFilter != ""
	artistFilter   string           // album-grid scope: "" = all, otherwise that artist name
	visibleAlbums  []*library.Album // recomputed when filter changes
	coverCache     map[*library.Album]fyne.Resource
}

// ── Layout ───────────────────────────────────────────────────────────────────

func buildUI(w fyne.Window, eng *audio.Engine, pl *playlist.Playlist, cfg *appConfig) *mainUI {
	ui := &mainUI{eng: eng, pl: pl, win: w, cfg: cfg, showLyrics: cfg.ShowLyrics}

	// ── Album art block ──────────────────────────────────────────────────
	// Min sizes are modest so the art can shrink for small windows (the
	// squareCenterLayout below grows it back up to fill the available
	// space). Lower MinSize → smaller window MinSize → the user can drag
	// the window down to laptop-screen sizes.
	ui.artBg = canvas.NewRectangle(colorBgElevated)
	ui.artBg.SetMinSize(fyne.NewSize(180, 180))
	ui.artBg.CornerRadius = 10

	ui.artGlyph = canvas.NewText("♪", color.NRGBA{R: 0xff, G: 0xff, B: 0xff, A: 0x55})
	ui.artGlyph.TextSize = 110
	ui.artGlyph.Alignment = fyne.TextAlignCenter
	ui.artGlyph.TextStyle = fyne.TextStyle{Bold: true}

	ui.artImage = &canvas.Image{}
	ui.artImage.FillMode = canvas.ImageFillContain
	ui.artImage.SetMinSize(fyne.NewSize(180, 180))
	ui.artImage.Hide()

	artStack := container.NewStack(
		ui.artBg,
		container.NewCenter(ui.artGlyph),
		ui.artImage,
	)

	// ── Track header text (title / artist / album) ───────────────────────
	ui.titleText = canvas.NewText("No track loaded", colorText)
	ui.titleText.TextSize = 28
	ui.titleText.TextStyle = fyne.TextStyle{Bold: true}
	ui.titleText.Alignment = fyne.TextAlignCenter

	ui.artistText = canvas.NewText("", colorText)
	ui.artistText.TextSize = 16
	ui.artistText.Alignment = fyne.TextAlignCenter

	ui.albumText = canvas.NewText("Open a file or folder to begin", colorTextDim)
	ui.albumText.TextSize = 13
	ui.albumText.Alignment = fyne.TextAlignCenter

	ui.formatText = canvas.NewText("", colorAccent)
	ui.formatText.TextSize = 12
	ui.formatText.TextStyle = fyne.TextStyle{Bold: true}
	ui.formatText.Alignment = fyne.TextAlignCenter

	headerBlock := container.NewVBox(
		ui.titleText,
		spacer(2),
		ui.artistText,
		ui.albumText,
		spacer(4),
		ui.formatText,
	)

	// ── Progress ─────────────────────────────────────────────────────────
	// The slider seeks on both drag AND click. OnChanged is called
	// continuously while the user drags, but the engine's Seek for DSD does
	// a full producer restart and Reset's oto's buffer for PCM — both are
	// disruptive if fired on every drag tick. So during a drag we just
	// update the UI labels; the actual eng.Seek runs once when OnChangeEnded
	// fires (drag release / click landed). For PCM that lands instantly; for
	// DSD it triggers the brief stop-restart.
	ui.posLabel = canvas.NewText("0:00", colorTextDim)
	ui.posLabel.TextSize = 11
	ui.durLabel = canvas.NewText("0:00", colorTextDim)
	ui.durLabel.TextSize = 11
	ui.durLabel.Alignment = fyne.TextAlignTrailing
	ui.modeLabel = canvas.NewText("", colorTextDim)
	ui.modeLabel.TextSize = 10
	ui.modeLabel.Alignment = fyne.TextAlignCenter

	ui.progress = widget.NewSlider(0, 1)
	ui.progress.Step = 0.0001
	ui.progress.OnChanged = func(v float64) {
		if ui.updatingUI {
			return
		}
		ui.seeking = true
		if eng.Info != nil {
			ui.posLabel.Text = fmtDuration(v * eng.Info.Duration)
			ui.posLabel.Refresh()
		}
	}
	ui.progress.OnChangeEnded = func(v float64) {
		// CRITICAL: Fyne's Slider.SetValue internally calls fireChangeEnded —
		// so every programmatic position update from OnPositionChange would
		// look like a "user finished a drag" event and trigger eng.Seek to
		// the position we just reported. For PCM that pulls pcmPos backwards
		// by the buffered-frames count (because Position() subtracts oto's
		// BufferedSize), the oto buffer then replays its older samples, and
		// the song appears to loop inside the first second. For DSD it
		// kicks off a full producer restart every 250 ms. The updatingUI
		// guard mirrors the one on OnChanged.
		if ui.updatingUI {
			return
		}
		if eng.Info != nil {
			eng.Seek(v * eng.Info.Duration)
		}
		// Release the lock that prevents the position timer from overwriting
		// the slider, but only after the engine has had a moment to refresh
		// internal counters — otherwise the very next position tick would
		// snap us back to the pre-seek frame.
		go func() {
			time.Sleep(60 * time.Millisecond)
			fyne.Do(func() { ui.seeking = false })
		}()
	}

	timeRow := container.New(layout.NewBorderLayout(nil, nil, ui.posLabel, ui.durLabel),
		ui.posLabel, ui.durLabel,
		container.NewCenter(ui.modeLabel),
	)

	progressBlock := container.NewVBox(
		ui.progress,
		timeRow,
	)

	// ── Transport controls ───────────────────────────────────────────────
	// Layout:  [shuffle]   ⏮  ⏹  ▶  ⏭   [repeat]
	// The play button is larger (HighImportance + container.NewGridWrap to
	// force a bigger min size) so it's the obvious primary target.
	prevBtn := iconButton(theme.MediaSkipPreviousIcon(), ui.goPrev)
	nextBtn := iconButton(theme.MediaSkipNextIcon(), ui.goNext)
	stopBtn := iconButton(theme.MediaStopIcon(), ui.stopPlayback)

	ui.playBtn = widget.NewButtonWithIcon("", theme.MediaPlayIcon(), ui.togglePlay)
	ui.playBtn.Importance = widget.HighImportance
	playSized := container.NewGridWrap(fyne.NewSize(56, 40), ui.playBtn)

	// Shuffle/repeat stay LowImportance (transparent background, white icon)
	// in BOTH active and inactive states — the user explicitly didn't want
	// the accent-green active highlight. State feedback is by the small dot
	// indicator below each button (toggled in refreshShuffleVisual /
	// toggleRepeat).
	ui.shuffleBtn = widget.NewButtonWithIcon("", shuffleIconResource, ui.toggleShuffle)
	ui.shuffleBtn.Importance = widget.LowImportance

	ui.repeatBtn = widget.NewButtonWithIcon("", repeatIconResource, ui.toggleRepeat)
	ui.repeatBtn.Importance = widget.LowImportance

	ui.shuffleDot = canvas.NewCircle(color.Transparent)
	ui.shuffleDot.StrokeWidth = 0
	ui.repeatDot = canvas.NewCircle(color.Transparent)
	ui.repeatDot.StrokeWidth = 0
	ui.refreshShuffleVisual()
	ui.refreshRepeatVisual()

	// Each toggle button is wrapped in a VBox over a tiny "dot" so the active
	// state is visible without changing the icon color.
	shuffleStack := container.NewVBox(
		ui.shuffleBtn,
		container.NewGridWrap(fyne.NewSize(6, 6), ui.shuffleDot),
	)
	repeatStack := container.NewVBox(
		ui.repeatBtn,
		container.NewGridWrap(fyne.NewSize(6, 6), ui.repeatDot),
	)

	transport := container.NewCenter(container.NewHBox(
		shuffleStack,
		spacerH(14),
		prevBtn,
		spacerH(6),
		stopBtn,
		spacerH(6),
		playSized,
		spacerH(6),
		nextBtn,
		spacerH(14),
		repeatStack,
	))

	// ── Volume ───────────────────────────────────────────────────────────
	volSlider := widget.NewSlider(0, 1)
	volSlider.Value = float64(eng.Volume) // restored from config
	volSlider.Step = 0.01
	volSlider.OnChanged = func(v float64) {
		eng.Volume = float32(v)
	}
	volSlider.OnChangeEnded = func(float64) {
		ui.cfg.Volume = eng.Volume
		ui.cfg.save()
	}
	volIcon := widget.NewIcon(theme.VolumeUpIcon())

	lyricsToggle := widget.NewButtonWithIcon("Lyrics", theme.DocumentIcon(), func() {
		ui.toggleLyrics()
	})
	lyricsToggle.Importance = widget.LowImportance

	volRow := container.New(layout.NewBorderLayout(nil, nil, volIcon, lyricsToggle),
		volIcon,
		lyricsToggle,
		volSlider,
	)

	// ── Waveform visualizer ──────────────────────────────────────────────
	ui.wave = newWaveformWidget(96)
	ui.wave.OnSeek = func(frac float64) {
		if eng.Info == nil {
			return
		}
		target := frac * eng.Info.Duration
		eng.Seek(target)
		// Update the progress slider immediately so it doesn't snap back.
		ui.updatingUI = true
		ui.progress.SetValue(frac)
		ui.updatingUI = false
		ui.wave.SetPosition(float32(frac))
	}
	waveBox := container.NewPadded(ui.wave)

	// ── Right column assembly (responsive) ───────────────────────────────
	// Border layout: art in the center grows to fill all vertical space the
	// window gives it; the controls block sticks to the bottom at its
	// natural height. This means making the window taller makes the art
	// bigger, not the controls.
	bottomBlock := container.NewVBox(
		container.NewPadded(headerBlock),
		spacer(6),
		waveBox,
		spacer(4),
		container.NewPadded(progressBlock),
		spacer(4),
		container.NewPadded(transport),
		spacer(2),
		container.NewPadded(volRow),
		spacer(8),
	)

	// Square-fit + center: the art grows to fill the available space while
	// keeping its aspect ratio. NewCenter alone would freeze it at MinSize.
	artArea := container.NewPadded(container.New(squareCenterLayout{}, artStack))

	// Ambient backdrop: a vertical gradient under the player column whose
	// top color is derived from the current track's album art. Starts fully
	// transparent (no album loaded yet) so the base theme background shows
	// through; applyMetadata fills it in once the cover is decoded.
	ui.bgGradient = canvas.NewVerticalGradient(
		color.NRGBA{},      // top — set per-track
		color.NRGBA{},      // bottom — set per-track (transparent fades to base bg)
	)

	rightColumn := container.NewStack(
		ui.bgGradient,
		container.NewBorder(
			spacer(12),  // top
			bottomBlock, // bottom — fixed natural height
			nil, nil,    // left, right
			artArea, // center — expands
		),
	)

	// ── Left column: playlist ────────────────────────────────────────────
	plHeader := canvas.NewText("PLAYLIST", colorTextDim)
	plHeader.TextSize = 11
	plHeader.TextStyle = fyne.TextStyle{Bold: true}

	addBtn := widget.NewButtonWithIcon("", theme.ContentAddIcon(), func() {
		dialog.ShowFolderOpen(func(lu fyne.ListableURI, err error) {
			if err != nil || lu == nil {
				return
			}
			pl.AddDir(lu.Path())
			ui.applyFilter(ui.searchEntry.Text) // re-evaluate any active filter
			if pl.Current < 0 && pl.Len() > 0 {
				pl.SetCurrent(0)
				if t := pl.CurrentTrack(); t != nil {
					ui.loadAndPlay(t.Path)
				}
			}
		}, w)
	})
	addBtn.Importance = widget.LowImportance

	plHeaderBar := container.NewBorder(nil, nil, container.NewPadded(plHeader), addBtn)

	// Search bar — hidden by default; Ctrl+F toggles + focuses it, Esc closes.
	// Filtering is a pure index remap: filtered[] holds canonical indices of
	// rows that match, the list reads through this remap, and selection maps
	// back to the canonical index so pl.SetCurrent operates on the real
	// playlist regardless of filter state.
	ui.searchEntry = widget.NewEntry()
	ui.searchEntry.SetPlaceHolder("Search title…")
	ui.searchEntry.OnChanged = func(q string) {
		ui.applyFilter(q)
	}
	clearSearchBtn := widget.NewButtonWithIcon("", theme.WindowCloseIcon(), func() {
		ui.hideSearchBar()
	})
	clearSearchBtn.Importance = widget.LowImportance
	ui.searchBar = container.NewBorder(nil, nil, nil, clearSearchBtn, ui.searchEntry)
	ui.searchBar.Hide()

	ui.listWidget = widget.NewList(
		func() int {
			if ui.filtered != nil {
				return len(ui.filtered)
			}
			return pl.Len()
		},
		func() fyne.CanvasObject {
			title := canvas.NewText("", colorText)
			title.TextSize = 13
			subtitle := canvas.NewText("", colorTextDim)
			subtitle.TextSize = 10
			return container.NewVBox(title, subtitle)
		},
		func(id widget.ListItemID, obj fyne.CanvasObject) {
			real := ui.rowToReal(id)
			if real < 0 || real >= pl.Len() {
				return
			}
			box := obj.(*fyne.Container)
			title := box.Objects[0].(*canvas.Text)
			subtitle := box.Objects[1].(*canvas.Text)

			t := pl.Tracks[real]
			ext := ""
			if x := filepath.Ext(t.Path); len(x) > 1 {
				ext = "  " + x[1:]
			}
			if real == pl.Current {
				title.Text = "▸  " + t.Title
				title.Color = colorAccent
				title.TextStyle = fyne.TextStyle{Bold: true}
			} else {
				title.Text = "    " + t.Title
				title.Color = colorText
				title.TextStyle = fyne.TextStyle{}
			}
			subtitle.Text = "    " + ext
			title.Refresh()
			subtitle.Refresh()
		},
	)
	ui.listWidget.OnSelected = func(id widget.ListItemID) {
		// Ignore selections triggered programmatically by syncListSelection
		// — they exist only to update the visual hover, NOT to re-load.
		if ui.suppressSelect {
			return
		}
		real := ui.rowToReal(id)
		if real < 0 || real >= pl.Len() {
			return
		}
		pl.SetCurrent(real) // keeps shuffle order consistent
		if t := pl.CurrentTrack(); t != nil {
			ui.loadAndPlay(t.Path)
		}
	}

	playlistPanel := container.NewBorder(
		container.NewVBox(container.NewPadded(plHeaderBar), ui.searchBar),
		nil, nil, nil,
		ui.listWidget,
	)
	// Three-tab sidebar: Playlist (the existing UI), Albums (cover grid),
	// Artists (drill-down list). buildLibraryTabs stores libTabs/albumGrid/
	// artistList on the mainUI so the scan callbacks can refresh later.
	leftColumn := ui.buildLibraryTabs(playlistPanel)

	// Drag-and-drop support
	w.SetOnDropped(func(_ fyne.Position, uris []fyne.URI) {
		added := false
		for _, u := range uris {
			p := u.Path()
			if playlist.IsSupported(p) {
				pl.Add(p)
				added = true
			}
		}
		if added {
			ui.applyFilter(ui.searchEntry.Text)
			if pl.Current < 0 || eng.CurrentState() == audio.StateStopped {
				pl.SetCurrent(pl.Len() - 1)
				if t := pl.CurrentTrack(); t != nil {
					ui.loadAndPlay(t.Path)
				}
			}
		}
	})

	// ── Lyrics panel (collapsed by default) ──────────────────────────────
	ui.lyricsHeader = canvas.NewText("LYRICS", colorTextDim)
	ui.lyricsHeader.TextSize = 11
	ui.lyricsHeader.TextStyle = fyne.TextStyle{Bold: true}

	ui.lyricsBox = container.NewVBox()
	ui.lyricsScroll = container.NewVScroll(container.NewPadded(ui.lyricsBox))

	closeLyricsBtn := widget.NewButtonWithIcon("", theme.WindowCloseIcon(), func() {
		ui.toggleLyrics()
	})
	closeLyricsBtn.Importance = widget.LowImportance

	lyricsHeaderBar := container.NewBorder(nil, nil,
		container.NewPadded(ui.lyricsHeader),
		closeLyricsBtn,
	)
	ui.lyricsPanel = container.NewBorder(
		container.NewPadded(lyricsHeaderBar),
		nil, nil, nil,
		ui.lyricsScroll,
	)
	ui.setEmptyLyrics("Open a track to see lyrics")

	// ── Compose final layout ─────────────────────────────────────────────
	ui.playerColumn = rightColumn
	ui.rightContainer = container.NewStack(rightColumn) // single child by default
	ui.mainSplit = container.NewHSplit(leftColumn, ui.rightContainer)
	ui.mainSplit.Offset = 0.26
	ui.root = ui.mainSplit

	// ── Engine callbacks ─────────────────────────────────────────────────
	eng.OnStateChange = func(s audio.State) {
		fyne.Do(func() {
			switch s {
			case audio.StatePlaying:
				ui.playBtn.SetIcon(theme.MediaPauseIcon())
			case audio.StateLoading:
				ui.formatText.Text = "Loading…"
				ui.formatText.Refresh()
			default:
				ui.playBtn.SetIcon(theme.MediaPlayIcon())
			}
		})
	}

	eng.OnPositionChange = func(pos, dur float64) {
		fyne.Do(func() {
			ui.posLabel.Text = fmtDuration(pos)
			ui.posLabel.Refresh()
			ui.durLabel.Text = fmtDuration(dur)
			ui.durLabel.Refresh()
			if dur > 0 && !ui.seeking {
				frac := float32(pos / dur)
				ui.updatingUI = true
				ui.progress.SetValue(float64(frac))
				ui.updatingUI = false
				ui.wave.SetPosition(frac)
			}
			if ui.showLyrics {
				ui.updateLyricsPosition(pos)
			}
			ui.maybePreloadNext(pos, dur)
			ui.refreshModeLabel(eng)
		})
	}

	// OnTrackTransition fires from inside the audio thread the moment a
	// preloaded next track first becomes audible (crossfade start). The
	// engine has already promoted the new pcmData internally — we just
	// need to align the UI (title / cover / progress / lyrics) and advance
	// the playlist cursor so subsequent Next/Prev are consistent.
	eng.OnTrackTransition = func(info *audio.FileInfo) {
		fyne.Do(func() {
			// Advance the playlist to the new track. PeekNext().Path is
			// what we Preloaded; matching by path lets shuffle ordering
			// stay correct even if the user mutated the list mid-track.
			for i, t := range pl.Tracks {
				if t.Path == info.Path {
					pl.SetCurrent(i)
					break
				}
			}
			ui.applyMetadata(info)
			ui.updatingUI = true
			ui.progress.SetValue(0)
			ui.updatingUI = false
			ui.posLabel.Text = "0:00"
			ui.posLabel.Refresh()
			ui.durLabel.Text = fmtDuration(info.Duration)
			ui.durLabel.Refresh()
			ui.wave.SetPosition(0)
			ui.syncListSelection()
			ui.setEmptyLyrics("Searching for lyrics…")

			// Fetch lyrics for the new track. Token bumped so any pending
			// fetch for the previous track gets dropped on arrival.
			ui.lyricsToken++
			token := ui.lyricsToken
			go func(info *audio.FileInfo, tok int) {
				lines := audio.FetchLyrics(info)
				fyne.Do(func() {
					if tok != ui.lyricsToken {
						return
					}
					ui.setLyrics(lines)
				})
			}(info, token)
		})
	}

	eng.OnError = func(msg string) {
		fyne.Do(func() {
			dialog.ShowError(fmt.Errorf("%s", msg), w)
		})
	}

	eng.OnFinished = func() {
		fyne.Do(func() {
			if ui.repeatTrack {
				if t := pl.CurrentTrack(); t != nil {
					ui.loadAndPlay(t.Path)
				}
				return
			}
			if t := pl.Next(); t != nil {
				ui.syncListSelection()
				ui.loadAndPlay(t.Path)
			}
		})
	}

	return ui
}

// ── Transport helpers ────────────────────────────────────────────────────────

func (ui *mainUI) goNext() {
	if t := ui.pl.Next(); t != nil {
		ui.syncListSelection()
		ui.loadAndPlay(t.Path)
	}
}

func (ui *mainUI) goPrev() {
	// "Prev within track" UX: if we're more than ~3 s into the song, restart
	// the current track instead of jumping to the previous one. Matches
	// every major player's prev-button behaviour and saves a lot of "oops
	// I meant restart" presses.
	if ui.eng.Info != nil && ui.eng.Position() > 3 {
		ui.eng.Seek(0)
		return
	}
	if t := ui.pl.Prev(); t != nil {
		ui.syncListSelection()
		ui.loadAndPlay(t.Path)
	}
}

func (ui *mainUI) stopPlayback() {
	ui.eng.Stop()
	ui.updatingUI = true
	ui.progress.SetValue(0)
	ui.updatingUI = false
	ui.posLabel.Text = "0:00"
	ui.posLabel.Refresh()
	ui.modeLabel.Text = ""
	ui.modeLabel.Refresh()
	ui.applyAccent(color.NRGBA{}) // restore default green / clear backdrop
	ui.wave.SetPosition(-1)       // hide cursor
}

func (ui *mainUI) seekRelative(deltaSec float64) {
	if ui.eng.Info == nil {
		return
	}
	target := ui.eng.Position() + deltaSec
	if target < 0 {
		target = 0
	}
	if target > ui.eng.Info.Duration {
		target = ui.eng.Info.Duration - 0.1
	}
	ui.eng.Seek(target)
}

func (ui *mainUI) toggleShuffle() {
	ui.pl.ToggleShuffle()
	ui.refreshShuffleVisual()
}

func (ui *mainUI) refreshShuffleVisual() {
	if ui.shuffleDot == nil {
		return
	}
	if ui.pl.Shuffle {
		ui.shuffleDot.FillColor = colorText
	} else {
		ui.shuffleDot.FillColor = color.Transparent
	}
	ui.shuffleDot.Refresh()
}

func (ui *mainUI) toggleRepeat() {
	ui.repeatTrack = !ui.repeatTrack
	ui.refreshRepeatVisual()
}

func (ui *mainUI) refreshRepeatVisual() {
	if ui.repeatDot == nil {
		return
	}
	if ui.repeatTrack {
		ui.repeatDot.FillColor = colorText
	} else {
		ui.repeatDot.FillColor = color.Transparent
	}
	ui.repeatDot.Refresh()
}

// installShortcuts wires keyboard control of playback. Single-key bindings
// (Space, Left, Right, S, L, R) go through Canvas.SetOnTypedKey; combinations
// with Ctrl go through Canvas.AddShortcut with a desktop.CustomShortcut.
//
// We also clear focus on every key press so that a focused button (e.g. the
// play button after a mouse click) does NOT also receive Space and toggle
// playback twice. The Fyne convention is that SetOnTypedKey fires whether or
// not anything is focused, but a focused Tappable will eat Space first — so
// we proactively unfocus on every shortcut fire and the keystroke routes
// only through our handler.
func (ui *mainUI) installShortcuts(w fyne.Window) {
	c := w.Canvas()

	unfocus := func() { c.Unfocus() }

	c.SetOnTypedKey(func(ev *fyne.KeyEvent) {
		// When the search entry has the keyboard, every printable / nav key
		// belongs to the editor, not to playback shortcuts. Esc closes the
		// bar (handled below); Enter just commits the current filter and
		// also closes. Everything else is forwarded to the entry by Fyne
		// automatically — we simply don't intercept it here.
		if c.Focused() == ui.searchEntry {
			switch ev.Name {
			case fyne.KeyEscape:
				ui.hideSearchBar()
			case fyne.KeyReturn, fyne.KeyEnter:
				unfocus()
			}
			return
		}

		switch ev.Name {
		case fyne.KeySpace:
			unfocus()
			ui.togglePlay()
		case fyne.KeyRight:
			ui.seekRelative(+5)
		case fyne.KeyLeft:
			ui.seekRelative(-5)
		case fyne.KeyUp:
			ui.adjustVolume(+0.05)
		case fyne.KeyDown:
			ui.adjustVolume(-0.05)
		case fyne.KeyS:
			ui.toggleShuffle()
		case fyne.KeyL:
			ui.toggleLyrics()
		case fyne.KeyR:
			ui.toggleRepeat()
		case fyne.KeyDelete:
			ui.removeCurrent()
		case fyne.KeyEscape:
			// Outside the search entry, Esc also clears any active filter.
			if ui.filtered != nil || (ui.searchBar != nil && ui.searchBar.Visible()) {
				ui.hideSearchBar()
			}
		}
	})

	// Modifier combos.
	addShortcut := func(key fyne.KeyName, mod fyne.KeyModifier, fn func()) {
		c.AddShortcut(&desktop.CustomShortcut{KeyName: key, Modifier: mod}, func(fyne.Shortcut) { fn() })
	}

	// Ctrl+←/→ jump tracks.
	addShortcut(fyne.KeyRight, fyne.KeyModifierControl, ui.goNext)
	addShortcut(fyne.KeyLeft, fyne.KeyModifierControl, ui.goPrev)
	// Ctrl+F focuses the playlist search bar.
	addShortcut(fyne.KeyF, fyne.KeyModifierControl, ui.showSearchBar)
	// Ctrl+Shift+↑/↓ reorder the playing track without interrupting playback.
	addShortcut(fyne.KeyUp, fyne.KeyModifierControl|fyne.KeyModifierShift, func() { ui.moveCurrent(-1) })
	addShortcut(fyne.KeyDown, fyne.KeyModifierControl|fyne.KeyModifierShift, func() { ui.moveCurrent(+1) })
}

func (ui *mainUI) adjustVolume(delta float64) {
	// We don't keep a slider reference, so volume is mutated directly on the
	// engine. The on-screen slider only updates next time the user opens its
	// row, but that's fine — keyboard volume adjustment is a power-user path.
	v := float64(ui.eng.Volume) + delta
	if v < 0 {
		v = 0
	}
	if v > 1 {
		v = 1
	}
	ui.eng.Volume = float32(v)
	ui.cfg.Volume = float32(v)
	ui.cfg.save()
}

// ── Crossfade ────────────────────────────────────────────────────────────────

// maybePreloadNext asks the engine to start decoding the next playlist
// track when the current one is close enough to its end that a crossfade
// could begin soon. Gated by:
//   - crossfade is enabled (>0)
//   - the current track is PCM (DSD doesn't crossfade)
//   - we're not in repeat-track mode (the engine would fade into a
//     different track than what we want to play next)
//   - there IS a next track to preload
//
// The threshold is crossfadeSec + 6 s so the decode has comfortably
// finished by the time the engine wants to fade. Called from
// OnPositionChange (4×/s), so the actual Preload call lands in the
// engine repeatedly — that's fine, Preload itself deduplicates by path
// and bails when something's already loaded / loading.
func (ui *mainUI) maybePreloadNext(pos, dur float64) {
	if ui.repeatTrack {
		return
	}
	cf := ui.eng.CrossfadeSeconds()
	if cf <= 0 {
		return
	}
	if ui.eng.Info != nil && ui.eng.Info.IsDSD {
		return
	}
	remaining := dur - pos
	if remaining > cf+6 {
		return
	}
	nxt := ui.pl.PeekNext()
	if nxt == nil {
		return
	}
	ui.eng.Preload(nxt.Path)
}

// toggleCrossfade flips crossfade between 0 (off) and 4 s (on). Persisted
// to config; the engine picks it up immediately (atomic store, no restart).
func (ui *mainUI) toggleCrossfade() {
	if ui.eng.CrossfadeSeconds() > 0 {
		ui.eng.SetCrossfade(0)
		ui.cfg.CrossfadeSec = 0
		ui.eng.ClearPreload()
	} else {
		ui.eng.SetCrossfade(4)
		ui.cfg.CrossfadeSec = 4
	}
	ui.cfg.save()
}

// toggleExclusiveMode flips WASAPI exclusive-vs-shared mode. The change
// only affects the NEXT Play() call — already-running playback finishes
// in whatever backend it opened with. The menu label reflects the new
// preference immediately so the user knows what they picked.
func (ui *mainUI) toggleExclusiveMode() {
	new := !ui.eng.ExclusiveMode()
	ui.eng.SetExclusiveMode(new)
	ui.cfg.ExclusiveMode = new
	ui.cfg.save()
}

// ── Search / filter ──────────────────────────────────────────────────────────

// rowToReal converts a visible-list row index into the canonical playlist
// index, honouring an active filter. -1 if out of range.
func (ui *mainUI) rowToReal(row int) int {
	if ui.filtered != nil {
		if row < 0 || row >= len(ui.filtered) {
			return -1
		}
		return ui.filtered[row]
	}
	if row < 0 || row >= ui.pl.Len() {
		return -1
	}
	return row
}

// realToRow is the inverse of rowToReal: turns a canonical playlist index
// into the corresponding visible-list row, or -1 if the track is currently
// hidden by an active filter.
func (ui *mainUI) realToRow(real int) int {
	if real < 0 {
		return -1
	}
	if ui.filtered == nil {
		if real >= ui.pl.Len() {
			return -1
		}
		return real
	}
	for row, r := range ui.filtered {
		if r == real {
			return row
		}
	}
	return -1
}

// syncListSelection refreshes the visible playlist AND updates Fyne's row
// hover/selection so it tracks the current playing song. Called from every
// path that changes pl.Current programmatically — auto-advance, prev/next,
// crossfade transition, album-from-library load. Without this the "▸"
// prefix and accent color move (via UpdateItem) but the system hover stays
// stuck on whatever row the user last clicked manually.
func (ui *mainUI) syncListSelection() {
	ui.listWidget.Refresh()
	row := ui.realToRow(ui.pl.Current)
	ui.suppressSelect = true
	defer func() { ui.suppressSelect = false }()
	if row < 0 {
		ui.listWidget.UnselectAll()
		return
	}
	ui.listWidget.Select(row)
	ui.listWidget.ScrollTo(row)
}

// applyFilter rebuilds `filtered` from the current query string. An empty
// query clears the filter (returns to showing every track).
func (ui *mainUI) applyFilter(q string) {
	q = strings.TrimSpace(strings.ToLower(q))
	if q == "" {
		ui.filtered = nil
	} else {
		ui.filtered = ui.filtered[:0]
		for i, t := range ui.pl.Tracks {
			if strings.Contains(strings.ToLower(t.Title), q) {
				ui.filtered = append(ui.filtered, i)
			}
		}
		if ui.filtered == nil {
			ui.filtered = []int{}
		}
	}
	ui.listWidget.Refresh()
}

// showSearchBar reveals the search row and focuses the entry. Called from
// Ctrl+F and the Edit menu.
func (ui *mainUI) showSearchBar() {
	if ui.searchBar == nil {
		return
	}
	ui.searchBar.Show()
	ui.win.Canvas().Focus(ui.searchEntry)
}

// hideSearchBar clears the query, drops the filter, and removes focus so
// the keyboard shortcuts route through SetOnTypedKey again.
func (ui *mainUI) hideSearchBar() {
	if ui.searchBar == nil {
		return
	}
	ui.searchEntry.SetText("")
	ui.applyFilter("")
	ui.searchBar.Hide()
	ui.win.Canvas().Unfocus()
}

// ── Playlist edit actions ────────────────────────────────────────────────────

// removeCurrent drops the playing track from the playlist and, if anything
// remains, jumps to the next one (which now sits at the old Current's index
// after the shift). With nothing left, playback fully stops.
func (ui *mainUI) removeCurrent() {
	if ui.pl.Current < 0 {
		return
	}
	wasPlaying := ui.eng.CurrentState() == audio.StatePlaying
	idx := ui.pl.Current
	ui.eng.Stop()
	ui.pl.Remove(idx)
	ui.applyFilter(ui.searchEntry.Text) // rebuild filter against new tracks
	ui.syncListSelection()
	if ui.pl.Len() == 0 {
		ui.stopPlayback()
		return
	}
	// Remove() already clamped Current; keep playing from there if we were
	// in the middle of a song so the deletion feels seamless.
	if wasPlaying {
		if t := ui.pl.CurrentTrack(); t != nil {
			ui.loadAndPlay(t.Path)
		}
	}
}

// moveCurrent shifts the playing track by `delta` rows (-1 = up, +1 = down).
// No-op at the boundaries. Doesn't interrupt playback.
func (ui *mainUI) moveCurrent(delta int) {
	if ui.pl.Current < 0 {
		return
	}
	to := ui.pl.Current + delta
	if to < 0 || to >= ui.pl.Len() {
		return
	}
	ui.pl.Move(ui.pl.Current, to)
	ui.applyFilter(ui.searchEntry.Text) // filtered indices may have shifted
	ui.syncListSelection()
}

// ── Actions ──────────────────────────────────────────────────────────────────

func (ui *mainUI) loadAndPlay(path string) {
	ui.lyricsToken++
	token := ui.lyricsToken

	// A user-initiated track change should drop any preload — otherwise
	// the engine might crossfade into a track the user no longer wants.
	ui.eng.ClearPreload()

	go func() {
		info, err := ui.eng.Load(path)
		if err != nil {
			fyne.Do(func() { dialog.ShowError(err, ui.win) })
			return
		}
		fyne.Do(func() {
			ui.applyMetadata(info)
			ui.updatingUI = true
			ui.progress.SetValue(0)
			ui.updatingUI = false
			ui.posLabel.Text = "0:00"
			ui.posLabel.Refresh()
			ui.wave.SetPosition(0)
			ui.durLabel.Text = fmtDuration(info.Duration)
			ui.durLabel.Refresh()
			ui.syncListSelection()
			ui.setEmptyLyrics("Searching for lyrics…")
		})
		if err := ui.eng.Play(); err != nil {
			fyne.Do(func() { dialog.ShowError(err, ui.win) })
		}

		// Fetch lyrics asynchronously — never block playback on a network call.
		go func(info *audio.FileInfo, tok int) {
			lines := audio.FetchLyrics(info)
			fyne.Do(func() {
				if tok != ui.lyricsToken {
					return // user moved on to another track; discard.
				}
				ui.setLyrics(lines)
			})
		}(info, token)
	}()
}

func (ui *mainUI) applyMetadata(info *audio.FileInfo) {
	// Title: prefer tag, fall back to filename.
	title := info.Title
	if title == "" {
		title = filepath.Base(info.Path)
	}
	ui.titleText.Text = title
	ui.titleText.Refresh()

	ui.artistText.Text = info.Artist
	ui.artistText.Refresh()

	album := info.Album
	if album == "" {
		album = "—"
	}
	ui.albumText.Text = album
	ui.albumText.Refresh()

	ui.formatText.Text = info.QualityLabel
	ui.formatText.Refresh()

	// Album art: real picture if available, otherwise a hash-tinted placeholder.
	// Either way, derive an accent color so the rest of the UI (gradient,
	// format label, waveform) can echo the current track's visual identity.
	if len(info.PictureData) > 0 {
		res := fyne.NewStaticResource("cover", info.PictureData)
		ui.artImage.Resource = res
		ui.artImage.Refresh()
		ui.artImage.Show()
		ui.artGlyph.Hide()
		// Reset accent immediately so the previous track's hue doesn't linger
		// for the ~30–50 ms the goroutine takes to decode and sample. The
		// brief flash to default green is less jarring than the previous
		// track's color still on screen with a new cover.
		ui.applyAccent(color.NRGBA{})
		// Decode + sample the cover off the UI goroutine: image.Decode of a
		// 500 KB JPEG takes long enough to be visible at load time. Token
		// guards against late results landing on a newer track.
		picBytes := info.PictureData
		tok := ui.lyricsToken // piggyback on the lyrics token — increments on every Load
		go func() {
			c, ok := dominantColor(picBytes)
			fyne.Do(func() {
				if tok != ui.lyricsToken {
					return // user moved on
				}
				if ok {
					ui.applyAccent(c)
				}
			})
		}()
	} else {
		ui.artImage.Hide()
		ui.artGlyph.Show()
		// Tint the placeholder rectangle by file hash so each track has a
		// distinct visual fingerprint, and reuse that same hue for the
		// ambient gradient so the player still feels track-aware even when
		// the file has no embedded art.
		sum := md5.Sum([]byte(info.Path))
		hashCol := color.NRGBA{
			R: 0x40 + (sum[0] >> 1),
			G: 0x40 + (sum[1] >> 1),
			B: 0x40 + (sum[2] >> 1),
			A: 0xff,
		}
		ui.artBg.FillColor = hashCol
		ui.artBg.Refresh()
		ui.applyAccent(hashCol)
	}
}

// applyAccent retints every UI element that follows the current track's
// dominant color: the ambient backdrop gradient, the quality / mode labels,
// and the waveform. Pass a zero-alpha color to restore the theme defaults
// (used during startup and after stop).
func (ui *mainUI) applyAccent(c color.NRGBA) {
	ui.currentAccent = c
	if c.A == 0 {
		// Reset to theme defaults.
		ui.bgGradient.StartColor = color.NRGBA{}
		ui.bgGradient.EndColor = color.NRGBA{}
		ui.bgGradient.Refresh()
		ui.formatText.Color = colorAccent
		ui.formatText.Refresh()
		ui.wave.SetAccent(color.NRGBA{})
		ui.refreshModeLabel(ui.eng)
		return
	}

	// Gradient: dominant color tinted way down at the top, fully transparent
	// at the bottom so the base bg shows through and the controls stay
	// readable. ~14% alpha is the sweet spot: visible hue without washing
	// the album art's contrast.
	ui.bgGradient.StartColor = tint(c, 0x24)
	ui.bgGradient.EndColor = color.NRGBA{}
	ui.bgGradient.Refresh()

	// Brightened version of the dominant color for text overlays — extracted
	// colors at native luminance often read as muddy on a near-black bg.
	bright := brighten(c, 0.45)
	ui.formatText.Color = bright
	ui.formatText.Refresh()

	ui.wave.SetAccent(c)

	// Mode label also follows the accent when exclusive mode is active.
	ui.refreshModeLabel(ui.eng)
}

func (ui *mainUI) togglePlay() {
	switch ui.eng.CurrentState() {
	case audio.StatePlaying:
		ui.eng.Pause()
	case audio.StatePaused:
		ui.eng.Play()
	case audio.StateStopped:
		if t := ui.pl.CurrentTrack(); t != nil {
			ui.loadAndPlay(t.Path)
		}
	}
}

// ── Menu ─────────────────────────────────────────────────────────────────────

func buildMenu(w fyne.Window, eng *audio.Engine, pl *playlist.Playlist, ui *mainUI) *fyne.MainMenu {
	openFile := fyne.NewMenuItem("Open File…", func() {
		fd := dialog.NewFileOpen(func(r fyne.URIReadCloser, err error) {
			if err != nil || r == nil {
				return
			}
			r.Close()
			path := r.URI().Path()
			if !playlist.IsSupported(path) {
				dialog.ShowError(fmt.Errorf("unsupported format: %s", filepath.Ext(path)), w)
				return
			}
			pl.Add(path)
			pl.SetCurrent(pl.Len() - 1)
			ui.applyFilter(ui.searchEntry.Text)
			ui.loadAndPlay(path)
		}, w)
		fd.SetFilter(storage.NewExtensionFileFilter([]string{".dsf", ".dff", ".flac", ".wav", ".mp3"}))
		fd.Show()
	})

	openFolder := fyne.NewMenuItem("Open Folder…", func() {
		dialog.ShowFolderOpen(func(lu fyne.ListableURI, err error) {
			if err != nil || lu == nil {
				return
			}
			pl.AddDir(lu.Path())
			ui.applyFilter(ui.searchEntry.Text)
			if t := pl.CurrentTrack(); t != nil {
				ui.loadAndPlay(t.Path)
			}
		}, w)
	})

	setMusicRoot := fyne.NewMenuItem("Set Music Root…", func() {
		dialog.ShowFolderOpen(func(lu fyne.ListableURI, err error) {
			if err != nil || lu == nil {
				return
			}
			ui.setMusicRoot(lu.Path())
		}, w)
	})

	rescanLibrary := fyne.NewMenuItem("Rescan Library", func() {
		if ui.cfg.MusicRoot == "" {
			dialog.ShowInformation("No music root",
				"Use \"Set Music Root…\" first to pick the folder to index.", w)
			return
		}
		ui.scanLibrary(ui.cfg.MusicRoot, true)
	})

	clearList := fyne.NewMenuItem("Clear Playlist", func() {
		eng.Stop()
		pl.Clear()
		ui.hideSearchBar() // drop any active filter so the empty list shows correctly
		ui.listWidget.Refresh()
		ui.titleText.Text = "No track loaded"
		ui.titleText.Refresh()
		ui.artistText.Text = ""
		ui.artistText.Refresh()
		ui.albumText.Text = "Open a file or folder to begin"
		ui.albumText.Refresh()
		ui.formatText.Text = ""
		ui.formatText.Refresh()
		ui.artImage.Hide()
		ui.artGlyph.Show()
		ui.artBg.FillColor = colorBgElevated
		ui.artBg.Refresh()
		ui.posLabel.Text = "0:00"
		ui.posLabel.Refresh()
		ui.durLabel.Text = "0:00"
		ui.durLabel.Refresh()
		ui.updatingUI = true
		ui.progress.SetValue(0)
		ui.updatingUI = false
	})

	// Edit menu — playlist manipulation. Shortcut hints are part of the
	// menu label since Fyne doesn't render OS-style accelerator badges.
	searchItem := fyne.NewMenuItem("Search…  (Ctrl+F)", ui.showSearchBar)
	moveUpItem := fyne.NewMenuItem("Move Up  (Ctrl+Shift+↑)", func() { ui.moveCurrent(-1) })
	moveDownItem := fyne.NewMenuItem("Move Down  (Ctrl+Shift+↓)", func() { ui.moveCurrent(+1) })
	removeItem := fyne.NewMenuItem("Remove Track  (Del)", ui.removeCurrent)

	// Crossfade toggle. The label shows the current state and flips on
	// click. Fyne doesn't auto-refresh menu labels, so after toggling we
	// rebuild the label and call w.MainMenu().Refresh().
	var crossfadeItem *fyne.MenuItem
	crossfadeLabel := func() string {
		if ui.eng.CrossfadeSeconds() > 0 {
			return fmt.Sprintf("Crossfade: %.0fs (click to disable)", ui.eng.CrossfadeSeconds())
		}
		return "Crossfade: off (click to enable 4s)"
	}
	crossfadeItem = fyne.NewMenuItem(crossfadeLabel(), func() {
		ui.toggleCrossfade()
		crossfadeItem.Label = crossfadeLabel()
		if mm := w.MainMenu(); mm != nil {
			mm.Refresh()
		}
	})

	// Exclusive-mode toggle. Same dynamic-label pattern as crossfade.
	// Hint to the user that it only kicks in on the next song since we
	// don't restart the active player just to swap backends.
	var exclusiveItem *fyne.MenuItem
	exclusiveLabel := func() string {
		if ui.eng.ExclusiveMode() {
			return "Exclusive mode: on (bit-perfect, mutes other apps)"
		}
		return "Exclusive mode: off (shared, other apps audible)"
	}
	exclusiveItem = fyne.NewMenuItem(exclusiveLabel(), func() {
		ui.toggleExclusiveMode()
		exclusiveItem.Label = exclusiveLabel()
		if mm := w.MainMenu(); mm != nil {
			mm.Refresh()
		}
	})

	return fyne.NewMainMenu(
		fyne.NewMenu("File",
			openFile, openFolder,
			fyne.NewMenuItemSeparator(),
			setMusicRoot, rescanLibrary,
			fyne.NewMenuItemSeparator(),
			clearList,
		),
		fyne.NewMenu("Edit",
			searchItem,
			fyne.NewMenuItemSeparator(),
			moveUpItem, moveDownItem, removeItem,
			fyne.NewMenuItemSeparator(),
			crossfadeItem, exclusiveItem,
		),
	)
}

// ── Helpers ──────────────────────────────────────────────────────────────────

func fmtDuration(s float64) string {
	if s < 0 {
		s = 0
	}
	d := time.Duration(s) * time.Second
	h := int(d.Hours())
	m := int(d.Minutes()) % 60
	sec := int(d.Seconds()) % 60
	if h > 0 {
		return fmt.Sprintf("%d:%02d:%02d", h, m, sec)
	}
	return fmt.Sprintf("%d:%02d", m, sec)
}

// spacer returns a fixed vertical-only spacer of the given height in pixels.
func spacer(h float32) fyne.CanvasObject {
	r := canvas.NewRectangle(color.Transparent)
	r.SetMinSize(fyne.NewSize(0, h))
	return r
}

// squareCenterLayout sizes every child to the largest square that fits within
// the container's bounds (min of width/height) and centers it. Used for the
// album-art stack so the cover grows with the window instead of staying
// pinned at its MinSize — container.NewCenter would constrain to MinSize and
// container.NewStack alone would stretch into a non-square rectangle.
type squareCenterLayout struct{}

func (squareCenterLayout) Layout(objs []fyne.CanvasObject, size fyne.Size) {
	side := size.Width
	if size.Height < side {
		side = size.Height
	}
	if side < 0 {
		side = 0
	}
	pos := fyne.NewPos((size.Width-side)/2, (size.Height-side)/2)
	sz := fyne.NewSize(side, side)
	for _, o := range objs {
		o.Resize(sz)
		o.Move(pos)
	}
}

func (squareCenterLayout) MinSize(objs []fyne.CanvasObject) fyne.Size {
	var m fyne.Size
	for _, o := range objs {
		s := o.MinSize()
		if s.Width > m.Width {
			m.Width = s.Width
		}
		if s.Height > m.Height {
			m.Height = s.Height
		}
	}
	return m
}

// spacerH returns a fixed horizontal-only spacer of the given width.
func spacerH(w float32) fyne.CanvasObject {
	r := canvas.NewRectangle(color.Transparent)
	r.SetMinSize(fyne.NewSize(w, 0))
	return r
}

// iconButton is a low-importance icon-only button used for prev/next/stop.
func iconButton(icon fyne.Resource, tap func()) *widget.Button {
	b := widget.NewButtonWithIcon("", icon, tap)
	b.Importance = widget.LowImportance
	return b
}

// ── Waveform animation loop ─────────────────────────────────────────────────

// runWaveformLoop pulls the latest audio envelope from the engine 30×/s and
// hands it to the waveform widget. Always running — the visualizer ring sits
// dormant when nothing's playing, so Waveform() just returns zeros (and the
// widget's smoothing eases the line back to flat).
func (ui *mainUI) runWaveformLoop() {
	const fps = 30
	const numPoints = 96
	const windowMs = 38 // a touch under 2 frames @ 30fps — feels responsive
	tick := time.NewTicker(time.Second / fps)
	defer tick.Stop()

	for range tick.C {
		if ui.wave == nil || ui.eng == nil || ui.eng.Vis == nil {
			continue
		}
		samples := ui.eng.Vis.Waveform(numPoints, windowMs)
		// Copy because the closure runs later on the UI thread.
		snap := make([]float32, len(samples))
		copy(snap, samples)
		fyne.Do(func() {
			ui.wave.SetValues(snap)
		})
	}
}

// ── Lyrics panel ─────────────────────────────────────────────────────────────

// toggleLyrics shows or hides the right-side lyrics panel by swapping the
// content of rightContainer. The window resizes the panel automatically.
func (ui *mainUI) toggleLyrics() {
	ui.showLyrics = !ui.showLyrics
	ui.rightContainer.RemoveAll()
	if ui.showLyrics {
		split := container.NewHSplit(ui.playerColumn, ui.lyricsPanel)
		split.Offset = 0.62
		ui.rightContainer.Add(split)
		// Snap the highlighted line into view if we already have lyrics.
		if len(ui.lyricsLines) > 0 && ui.eng.Info != nil {
			ui.updateLyricsPosition(ui.eng.Position())
		}
	} else {
		ui.rightContainer.Add(ui.playerColumn)
	}
	ui.rightContainer.Refresh()
}

// setEmptyLyrics replaces the panel contents with a single status line.
// Used while waiting for the network fetch or when no lyrics are found.
func (ui *mainUI) setEmptyLyrics(message string) {
	ui.lyricsLines = nil
	ui.currentLyric = -1
	ui.lyricsBox.RemoveAll()
	t := canvas.NewText(message, colorTextDim)
	t.TextSize = 13
	t.Alignment = fyne.TextAlignCenter
	ui.lyricsBox.Add(t)
	ui.lyricsBox.Refresh()
}

// setEmptyLyricsWithRetry shows the empty-state message plus a "Retry" button
// that re-runs the lyrics lookup for the currently-loaded track. Used when
// the first fetch came back empty (no LRC, no embedded tag, nothing on
// LRCLIB) so the user can re-attempt after they're back online or after
// LRCLIB has been updated. The cached negative result is invalidated before
// the new lookup so the same empty answer can't short-circuit the retry.
func (ui *mainUI) setEmptyLyricsWithRetry(message string) {
	ui.lyricsLines = nil
	ui.currentLyric = -1
	ui.lyricsBox.RemoveAll()

	t := canvas.NewText(message, colorTextDim)
	t.TextSize = 13
	t.Alignment = fyne.TextAlignCenter

	retryBtn := widget.NewButtonWithIcon("Retry lookup", theme.ViewRefreshIcon(), func() {
		info := ui.eng.Info
		if info == nil {
			return
		}
		// Drop the cached empty result and re-query. Use the same search
		// title that FetchLyrics derives (track-number prefix stripped from
		// the tag title, falling back to the filename base).
		artist := info.Artist
		title := info.Title
		if title == "" {
			title = strings.TrimSuffix(filepath.Base(info.Path), filepath.Ext(info.Path))
		}
		audio.ClearLyricsCacheFor(artist, title)

		ui.lyricsToken++
		tok := ui.lyricsToken
		ui.setEmptyLyrics("Searching for lyrics…")
		go func(info *audio.FileInfo, tok int) {
			lines := audio.FetchLyrics(info)
			fyne.Do(func() {
				if tok != ui.lyricsToken {
					return
				}
				ui.setLyrics(lines)
			})
		}(info, tok)
	})
	retryBtn.Importance = widget.LowImportance

	ui.lyricsBox.Add(t)
	ui.lyricsBox.Add(container.NewCenter(retryBtn))
	ui.lyricsBox.Refresh()
}

// setLyrics replaces the panel contents with the given lines, prepared for
// position-driven highlighting (synced) or static display (plain).
func (ui *mainUI) setLyrics(lines []audio.LyricLine) {
	if len(lines) == 0 {
		ui.setEmptyLyricsWithRetry("No lyrics found")
		return
	}
	ui.lyricsLines = lines
	ui.currentLyric = -1
	ui.lyricsBox.RemoveAll()
	for _, ln := range lines {
		t := canvas.NewText(ln.Text, colorTextDim)
		t.TextSize = 14
		t.Alignment = fyne.TextAlignCenter
		ui.lyricsBox.Add(t)
	}
	ui.lyricsBox.Refresh()
	ui.lyricsScroll.ScrollToTop()
}

// Lyric styling constants — keep activation/deactivation visually consistent.
//
// Sizes are calibrated for an "Apple Music desktop" feel: active line is
// dramatically larger than the surrounding idle lines so it commands focus
// even when the panel is glanced at from across the room. Adjacent lines
// take a middle size (lyricSizeNear) so the transition between idle and
// active doesn't feel like a hard step.
const (
	lyricSizeIdle      float32 = 14
	lyricSizeNear      float32 = 16
	lyricSizeActive    float32 = 22
	lyricAnimDur               = 200 * time.Millisecond
	lyricScrollDur             = 420 * time.Millisecond
	lyricLineHeightHint        = float32(32)
)

// updateLyricsPosition highlights the line whose timestamp matches the current
// playback position and scrolls it into view. No-op for plain (unsynced)
// lyrics — those just sit there.
//
// Visual treatment (depth-of-field, Apple-Music-inspired):
//   - The new active line fades to the album's accent color, bolds, and grows
//     to lyricSizeActive (22 px).
//   - Lines immediately above/below (±1) take an intermediate size and full
//     white color, so the transition into the active band is smooth.
//   - Everything else relaxes back to colorTextDim @ lyricSizeIdle.
//   - The scroll glides to center the active line in the viewport.
//
// Any animations still in flight from the previous line change are stopped
// before new ones start, so rapid line changes can't pile up.
func (ui *mainUI) updateLyricsPosition(posSec float64) {
	if len(ui.lyricsLines) == 0 {
		return
	}
	if !ui.lyricsLines[0].IsSynced() {
		return
	}
	target := time.Duration(posSec * float64(time.Second))
	idx := -1
	for i, ln := range ui.lyricsLines {
		if ln.Time <= target {
			idx = i
		} else {
			break
		}
	}
	if idx == ui.currentLyric {
		return
	}
	prev := ui.currentLyric
	ui.currentLyric = idx

	ui.stopLyricAnims()

	// Build the set of lines whose visual state changes this cycle: the new
	// active, its ±1 neighbors, plus the previously-active and ITS neighbors
	// so they relax back to idle as the focus moves. Using a set avoids
	// double-animating the same line when prev and idx are adjacent.
	touched := map[int]struct{}{}
	for _, i := range []int{prev - 1, prev, prev + 1, idx - 1, idx, idx + 1} {
		if i >= 0 && i < len(ui.lyricsBox.Objects) {
			touched[i] = struct{}{}
		}
	}

	// Accent for the active line follows the album's dominant color when
	// available, falling back to the static green so first-frame loads still
	// have a highlight.
	activeCol := color.Color(colorAccent)
	if ui.currentAccent.A != 0 {
		activeCol = brighten(ui.currentAccent, 0.45)
	}

	for i := range touched {
		t, ok := ui.lyricsBox.Objects[i].(*canvas.Text)
		if !ok {
			continue
		}
		switch i {
		case idx:
			t.TextStyle = fyne.TextStyle{Bold: true}
			ui.animateLineTo(t, activeCol, lyricSizeActive)
		case idx - 1, idx + 1:
			t.TextStyle = fyne.TextStyle{}
			ui.animateLineTo(t, colorText, lyricSizeNear)
		default:
			t.TextStyle = fyne.TextStyle{}
			ui.animateLineTo(t, colorTextDim, lyricSizeIdle)
		}
	}

	if idx >= 0 {
		viewportH := ui.lyricsScroll.Size().Height
		desiredY := float32(idx)*lyricLineHeightHint - viewportH/2 + lyricLineHeightHint
		if desiredY < 0 {
			desiredY = 0
		}
		ui.animateScrollTo(desiredY)
	}
}

// stopLyricAnims halts every in-flight color/size animation on the lyric
// lines plus the scroll animation. Leaves the canvas in whatever intermediate
// state it was in — the next animateLineTo / animateScrollTo will start from
// there, so transitions stay visually continuous.
func (ui *mainUI) stopLyricAnims() {
	for _, a := range ui.lineAnims {
		if a != nil {
			a.Stop()
		}
	}
	ui.lineAnims = ui.lineAnims[:0]
	if ui.scrollAnim != nil {
		ui.scrollAnim.Stop()
		ui.scrollAnim = nil
	}
}

// animateLineTo runs a paired color + size animation on a single lyric line.
// Both start from the line's current rendered state so a stopped-mid-flight
// previous animation continues smoothly from where it was.
func (ui *mainUI) animateLineTo(t *canvas.Text, toCol color.Color, toSize float32) {
	fromCol := t.Color
	if fromCol == nil {
		fromCol = colorTextDim
	}
	fromSize := t.TextSize
	if fromSize <= 0 {
		fromSize = lyricSizeIdle
	}

	colorAnim := canvas.NewColorRGBAAnimation(fromCol, toCol, lyricAnimDur, func(c color.Color) {
		t.Color = c
		t.Refresh()
	})
	colorAnim.Curve = fyne.AnimationEaseOut
	colorAnim.Start()

	sizeAnim := fyne.NewAnimation(lyricAnimDur, func(f float32) {
		t.TextSize = fromSize + (toSize-fromSize)*f
		t.Refresh()
	})
	sizeAnim.Curve = fyne.AnimationEaseOut
	sizeAnim.Start()

	ui.lineAnims = append(ui.lineAnims, colorAnim, sizeAnim)
}

// animateScrollTo glides the lyrics viewport offset to y over lyricScrollDur.
// Uses ease-in-out so the motion feels deliberate rather than abrupt.
func (ui *mainUI) animateScrollTo(y float32) {
	if ui.lyricsScroll == nil {
		return
	}
	start := ui.lyricsScroll.Offset.Y
	if start == y {
		return
	}
	anim := fyne.NewAnimation(lyricScrollDur, func(f float32) {
		ui.lyricsScroll.Offset = fyne.NewPos(0, start+(y-start)*f)
		ui.lyricsScroll.Refresh()
	})
	anim.Curve = fyne.AnimationEaseInOut
	anim.Start()
	ui.scrollAnim = anim
}

// refreshModeLabel updates the audio output mode indicator in the time row.
// Exclusive follows the current track's accent (brightened for legibility on
// a dark background); shared stays dim gray. Updates every ticker tick and
// every track load so the color stays in sync with the album art.
func (ui *mainUI) refreshModeLabel(eng *audio.Engine) {
	mode := eng.OutputMode()
	var text string
	var col color.Color
	switch mode {
	case "exclusive":
		text = "EXCLUSIVE"
		if ui.currentAccent.A != 0 {
			col = brighten(ui.currentAccent, 0.45)
		} else {
			col = colorAccent
		}
	case "shared":
		text = "SHARED"
		col = colorTextDim
	default:
		text = ""
		col = colorTextDim
	}
	ui.modeLabel.Text = text
	ui.modeLabel.Color = col
	ui.modeLabel.Refresh()
}
